// Top 70 Binance Futures symbols used for Chaos‑Mode stress testing.
// List curated from Binance volume rankings (as of 2026).
const TOP_SYMBOLS = [
  'BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','AVAXUSDT','LINKUSDT','DOTUSDT',
  'LTCUSDT','MATICUSDT','POLUSDT','ARBUSDT','OPUSDT','NEARUSDT','INJUSDT','SUIUSDT','FTMUSDT','APTUSDT',
  'BCHUSDT','ATOMUSDT','ETCUSDT','XLMUSDT','FILUSDT','GALAUSDT','CHZUSDT','1000BONKUSDT','BONKUSDT','JTOUSDT',
  'PYTHUSDT','JUPUSDT','STRKUSDT','ORDIUSDT','LDOUSDT','CRVUSDT','AAVEUSDT','SNXUSDT','EOSUSDT','ZILUSDT',
  'VETUSDT','MKRUSDT','ALGOUSDT','KSMUSDT','RUNEUSDT','CAKEUSDT','COMPUSDT','LRCUSDT','SKLUSDT','XMRUSDT',
  'ZRXUSDT','RVNUSDT','DASHUSDT','XECUSDT','FTTUSDT','HBARUSDT','BTTUSDT','STMXUSDT','ENJUSDT','GRTUSDT',
  'TRXUSDT','KAVAUSDT','WAVESUSDT','YFIUSDT','LUNA2USDT','GTCUSDT','CHRBUSDT','SANDUSDT','MANAUSDT','AXSUSDT'
];
module.exports = { TOP_SYMBOLS };
