FUTURES_SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT",
    "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "LINKUSDT", "DOTUSDT",
    "POLUSDT", "LTCUSDT", "BCHUSDT", "UNIUSDT", "ATOMUSDT",
    "ETCUSDT", "XLMUSDT", "FILUSDT", "APTUSDT", "ARBUSDT",
    "OPUSDT", "NEARUSDT", "INJUSDT", "SUIUSDT", "TIAUSDT",
    "SEIUSDT", "WLDUSDT", "STXUSDT", "RUNEUSDT", "FTMUSDT",
    "SANDUSDT", "MANAUSDT", "AXSUSDT", "GALAUSDT", "ENJUSDT",
    "CHZUSDT", "1000SHIBUSDT", "1000PEPEUSDT", "1000FLOKIUSDT", "1000BONKUSDT",
    "JTOUSDT", "PYTHUSDT", "JUPUSDT", "WUSDT", "STRKUSDT",
    "ORDIUSDT", "1000SATSUSDT", "LDOUSDT", "CRVUSDT", "AAVEUSDT",
]

# Spot symbols — placeholder for future phase
# SPOT_SYMBOLS = []

SUPPORTED_TIMEFRAMES = ["1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d", "3d", "1w"]

SUPPORTED_EXCHANGES = ["Binance Futures", "Binance Spot"]

DEFAULT_BATCH_SIZE = 1000  # Binance maximum per request
